### ISSUE TITLE
ModuleNotFoundError: No module named 'bluesky_live'

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/use_bluesky#84]
With new release of databroker, we have gained a dependency on a [`bluesky-live`](https://github.com/bluesky/bluesky-live) module that is in early stages of development (0.0.6).

```
(/share1/bluesky/conda_envs/bluesky_2021_1) bash-4.2$ blueskyUSAXS 
Python 3.8.2 (default, Mar 26 2020, 15:53:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

IPython profile: bluesky
Activating auto-logging. Current session state plus future input saved.
Filename       : /home/beams11/USAXS/.ipython/.logs/ipython_console.log
Mode           : rotate
Output logging : True
Raw input log  : False
Timestamping   : True
State          : active
I Mon-11:35:46 - ############################################################ startup
I Mon-11:35:46 - logging started
I Mon-11:35:46 - logging level = 10
I Mon-11:35:46 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/collection.py
I Mon-11:35:46 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/mpl/console.py
I Mon-11:35:47 - bluesky framework
I Mon-11:35:47 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/framework/check_python.py
I Mon-11:35:47 - /home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/framework/initialize.py
2020-12-21 11:35:49,657 - intake - ERROR - discovery.py:autodiscover:L147 - Error while loading entrypoint bluesky-event-stream
Traceback (most recent call last):
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/intake/source/discovery.py", line 250, in _load_entrypoint
    return entrypoint.load()
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/databroker/core.py", line 30, in <module>
    from bluesky_live.conversion import documents_to_xarray, documents_to_xarray_config
ModuleNotFoundError: No module named 'bluesky_live'
```

The `bluesky-live` package is not available from conda yet, just [PyPI](https://pypi.org/project/bluesky-live/), so add it to the post-conda pip installs.

**Comment by prjemian** [comment]
@danielballan : Just got bitten by this dependency.  Adding it to our standard environment for 2021-1 operations.
